# specify the node base image with your desired version node:<version>
ARG NODE_VERSION=24.15.0

FROM node:${NODE_VERSION} AS build

ARG APP_DIR

COPY ./src $APP_DIR/src

COPY package.json $APP_DIR

COPY tsconfig.build.json $APP_DIR

COPY tsconfig.json $APP_DIR

COPY .yarnrc.yml $APP_DIR

COPY yarn.lock $APP_DIR

COPY .yarn $APP_DIR/.yarn

WORKDIR $APP_DIR

RUN corepack enable yarn \
    && yarn set version stable \
    && yarn config set --home enableTelemetry 0 \
    && yarn install

RUN yarn build 


FROM node:${NODE_VERSION} as deploy

ARG APP_DIR

ENV NODE_ENV=production

COPY ./sequelize $APP_DIR/sequelize

COPY .sequelizerc $APP_DIR

COPY entrypoint.sh $APP_DIR

RUN chmod +x $APP_DIR/entrypoint.sh

COPY --from=build $APP_DIR/dist $APP_DIR/dist

COPY --from=build $APP_DIR/package.json $APP_DIR

COPY --from=build $APP_DIR/node_modules $APP_DIR/node_modules

WORKDIR $APP_DIR

ENTRYPOINT ["./entrypoint.sh"]

